name: Android Build

on:
  workflow_dispatch:

env:
  HAXE_VER: 4.3.7

jobs:
  android:
    name: Build Android
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2.1.0
        with:
          haxe-version: ${{ env.HAXE_VER }}

      - name: Authenticate Git
        run: |
          git config --global url."https://${{ secrets.ORG_PAT_TOKEN }}@github.com/".insteadOf "git@github.com:"

      - name: Install HMM
        run: |
          haxelib install hmm --quiet
          haxelib run hmm setup

      - name: Install Libraries
        run: |
          haxelib run hmm install

      # Instalar hxdiscord_rpc manualmente
      - name: Install hxdiscord_rpc
        run: |
          haxelib remove hxdiscord_rpc || true
          haxelib git hxdiscord_rpc https://github.com/FunkinPortingMobile/hxdiscord_rpc-android-support.git master

      - name: Rebuild hxcpp
        run: |
          haxelib run lime rebuild hxcpp --quiet

      - name: Configure Android
        run: |
          haxelib run lime setup android
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile Android
        run: |
          haxelib run lime build android -release

      - name: Upload APK
        uses: actions/upload-artifact@v7.0.1
        with:
          name: PsychEngine-Android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
